site_name: ClrSlate Tech Labs
site_author: Piyush Rathi
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette: 
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - announce.dismiss
nav:
  - Home: index.md
  - Product:
      - "Cloud Agnostic and Self-Hosted Kubernetes Solution": product/cloud_agnostic_kubernetes.md
      - "Integrated DevOps Tooling": product/integrated_devops_tooling.md
      - "Multi-Tenancy and Cost Accountability": product/multi_tenancy_cost_accountability.md
      - "Application Blueprints": product/application_blueprints.md
      - "Marketplace": product/marketplace.md
      - "Backup and Recovery": product/backup_recovery.md
      - "Developer Portal with Backstage": product/developer_portal_backstage.md
      - "Infrastructure as Code (IaC) with Terraform": product/iac_terraform.md
      - "Secrets Management": product/secrets_management.md
      - "Cost Management and Accountability": product/cost_management_accountability.md
      - "Compliance and Governance": product/compliance_governance.md
      - "Observability and Monitoring": product/observability_monitoring.md
  - About Us:
      - "Contact Us": about/contact.md
      - "Our Mission": about/mission.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/clrslate
    - icon: fontawesome/solid/paper-plane
      link: mailto:info@clrslate.io
copyright: Copyright &copy; 2024 ClrSlate Tech Labs Private Limited
